/**
 * Typed access to the migrated Shopify blog corpus.
 * Source of truth: src/data/blogs.json (generated by scripts/import-blogs.mjs).
 *
 * URL contract: every blog renders at /blogs/blog/<handle> — this MUST match
 * the existing Shopify URLs to preserve search rankings.
 */
import blogsJson from "@/data/blogs.json";

export interface Blog {
  title: string;
  handle: string;
  content: string; // HTML body, rendered as-is
  author: string | null;
  tags: string[];
  shopifyId: string | null;
  blogId: string | null;
  articleId: string | null;
  seoTitle: string | null;
  seoDescription: string | null;
  /**
   * Local path under /public to a cover image — null when no file is present.
   * Populated by scripts/sync-blog-images.mjs after files land in
   * /public/blog-images/. Path is web-relative (e.g. "/blog-images/foo.jpg").
   */
  coverImage: string | null;
}

const ALL: Blog[] = blogsJson as Blog[];

/** Returns the canonical pathname for a blog handle. */
export function blogPath(handle: string): string {
  return `/blogs/blog/${handle}`;
}

/** All blogs, newest first (sorted by import script). */
export function getAllBlogs(): Blog[] {
  return ALL;
}

/** All handles — used by generateStaticParams. */
export function getAllBlogHandles(): string[] {
  return ALL.map((b) => b.handle);
}

/** Look a blog up by its Shopify handle. */
export function getBlogByHandle(handle: string): Blog | null {
  return ALL.find((b) => b.handle === handle) ?? null;
}

/** Derive a short plain-text excerpt from HTML content for SEO descriptions. */
export function getExcerpt(blog: Blog, maxChars = 160): string {
  if (blog.seoDescription) return blog.seoDescription;
  const text = blog.content
    .replace(/<[^>]+>/g, " ")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/\s+/g, " ")
    .trim();
  if (text.length <= maxChars) return text;
  return text.slice(0, maxChars - 1).replace(/\s+\S*$/, "") + "…";
}
